name: Monthly rehearsal — previous-season fetch (no commit)

on:
  schedule:
    # Kjør månedlig den 1. kl. 22:00 UTC
    - cron: '0 22 1 * *'

permissions:
  contents: read  # hindrer push/commit

jobs:
  rehearsal_fetch_prev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (no credentials)
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # gjør push umulig

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run previous-season fetch (dry run)
        env:
          DRY_RUN: "1"   # bruk i skriptet for å hoppe over skriving/push
        run: python src/scripts/fetch_prev_season.py

      - name: Fail if repo changed (no writes allowed)
        run: |
          if ! git diff --quiet; then
            echo "Workspace changed — rehearsal must not write files."
            git status --porcelain
            git diff --stat
            exit 1
          fi
