name: Annual previous-season fetch

on:
  schedule:
    # Kjør hvert år 9. august kl. 22:00 UTC
    - cron: '0 22 10 8 *'

jobs:
  fetch_prev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Hent forrige sesong og kjør pipeline
        run: python src/scripts/fetch_prev_season.py

