name: Run update_all.py daily

permissions:
  contents: write

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 01:00 UTC every day
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run update_all.py
        run: |
          python -m src.scripts.update_all

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/raw data/processed/ data/models/
          git commit -m "Daily update: run update_all.py" || echo "No changes to commit"
          git push
