name: Run update_all.py daily

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 03:00 UTC every day
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update_all.py
        run: |
          python -m src.scripts.update_all

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/processed/ data/models/
          git commit -m "Daily update: run update_all.py" || echo "No changes to commit"
          git push
